"""expand_resume_model

Revision ID: 068ea3d2c082
Revises: a8fc730d3396
Create Date: 2026-07-06 15:55:09.662034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068ea3d2c082'
down_revision: Union[str, None] = 'a8fc730d3396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('resumes')]

    # List of columns to add with their types
    cols_to_add = [
        ('title', sa.Column('title', sa.String(length=255), nullable=False, server_default='My Resume')),
        ('description', sa.Column('description', sa.Text(), nullable=True)),
        ('version', sa.Column('version', sa.String(length=50), nullable=True)),
        ('file_url', sa.Column('file_url', sa.String(length=512), nullable=False)),
        ('file_name', sa.Column('file_name', sa.String(length=255), nullable=False)),
        ('thumbnail_url', sa.Column('thumbnail_url', sa.String(length=512), nullable=True)),
        ('file_size', sa.Column('file_size', sa.Integer(), nullable=False)),
        ('mime_type', sa.Column('mime_type', sa.String(length=100), nullable=False)),
        ('is_featured', sa.Column('is_featured', sa.Boolean(), nullable=False)),
        ('display_order', sa.Column('display_order', sa.Integer(), nullable=False)),
        ('created_by', sa.Column('created_by', sa.String(length=255), nullable=True)),
        ('updated_by', sa.Column('updated_by', sa.String(length=255), nullable=True)),
    ]

    for name, col_obj in cols_to_add:
        if name not in columns:
            op.add_column('resumes', col_obj)

    # Columns to drop
    if 'resume_filename' in columns:
        op.drop_column('resumes', 'resume_filename')
    if 'resume_url' in columns:
        op.drop_column('resumes', 'resume_url')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('resume_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('resumes', 'updated_by')
    op.drop_column('resumes', 'created_by')
    op.drop_column('resumes', 'display_order')
    op.drop_column('resumes', 'is_featured')
    op.drop_column('resumes', 'mime_type')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'thumbnail_url')
    op.drop_column('resumes', 'file_name')
    op.drop_column('resumes', 'file_url')
    op.drop_column('resumes', 'version')
    op.drop_column('resumes', 'description')
    # ### end Alembic commands ###
