"""add favicon_url to profile

Revision ID: a8fc730d3396
Revises: fd65a30f8473
Create Date: 2026-07-06 13:38:50.987672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fc730d3396'
down_revision: Union[str, None] = 'fd65a30f8473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    if 'favicon_url' not in columns:
        op.add_column('profiles', sa.Column('favicon_url', sa.String(length=512), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'favicon_url')
    # ### end Alembic commands ###
